######################################################################
# Automatically generated by qmake (2.01a) mar. mai 29 21:52:38 2012
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += app.cpp
RESOURCES += assets.qrc

QT += webkit
